config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, presence: true, numericality: { only_integer: true, in: (0..5)}
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food Finder</title>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render '/shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORIES %>
  <%= f.submit 'Add restaurant', class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/_restaurant_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORIES %>
  <%= f.submit 'Add restaurant', class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/_review_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <div class="star-rating">
    <% 5.times do |i| %>
      <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
    <% end %>
  </div>
  <%= f.input :content%>
  <%= f.submit 'Submit review', class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container my-4">
  <h2>Restaurants</h2>
  <div class="cards my-3"> 
    <% @restaurants.each do |restaurant| %>
      <div class="card-trip">
        <%= image_tag "https://loremflickr.com/320/240/#{restaurant.category}food" %>
        <div class="card-trip-infos">
          <div>
            <h2><%= restaurant.name %></h2>
            <p><%= restaurant.address %></p>
            <p><%= restaurant.phone_number %></p>
          </div>
          <h2 class="card-trip-pricing"><%= restaurant.category.capitalize %></h2>
        </div>
        <%= link_to '', restaurant_path(restaurant), class: 'card-link' %> 
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-4">
  <h2>Add a restaurant</h2>
  <%= render 'restaurant_form' %>
</div>

app/views/restaurants/show.html.erb
<div class="container mt-4">
  <div class="container d-flex align-items-center my-4">
    <%= image_tag "https://loremflickr.com/320/240/#{@restaurant.category}food", class: 'restaurant-img' %>
    <div class="restaurant-info mx-4">
      <h2><%= @restaurant.name %></h2>
      <p class="m-0" ><%= @restaurant.address %></p>
      <p class="m-0"><%= @restaurant.phone_number %></p>
      <p><strong>Category:</strong> <%= @restaurant.category.capitalize %></p>
    </div>
  </div>
  <h3>Reviews</h3>
  <div class="cards mt-3">
    <% if @restaurant.reviews.any? %>
      <% @restaurant.reviews.each do |review| %>
        <div class="card-product">
          <div class="card-product-infos">
            <div class="d-flex">
              <% review.rating.times do %>
                <i class="fas fa-star"></i>
              <% end %>
              <% (5 - review.rating).times do %>
                <i class="far fa-star"></i>
              <% end %>
            </div>
            <p><%= review.content %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="container mt-5">
    <h4>Add a review</h4>
    <%= render 'review_form' %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <div class="star-rating">
    <% 5.times do |i| %>
      <input type="radio" name="review[rating]" value="<%= i + 1 %>" <%= "checked" if i == 2 %> />
    <% end %>
  </div>
  <%= f.input :content%>
  <%= f.submit 'Submit review', class: 'btn btn-primary' %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="/restaurants">
      <i class="fa-solid fa-utensils"></i><span> Food Finder</span>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to 'Add restaurant', new_restaurant_path, class: 'btn btn-light' %>
          </li>
          <li class="nav-item dropdown">
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>